set_location_assignment PIN_E21 -to led_o[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[0]
set_location_assignment PIN_E22 -to led_o[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[1]
set_location_assignment PIN_E25 -to led_o[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[2]
set_location_assignment PIN_E24 -to led_o[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[3]
set_location_assignment PIN_H21 -to led_o[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[4]
set_location_assignment PIN_G20 -to led_o[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[5]
set_location_assignment PIN_G22 -to led_o[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[6]
set_location_assignment PIN_G21 -to led_o[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to led_o[7]

